name: Run Katalon API Tests

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  katalon-api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Katalon API Test Suite
        run: |
          docker run --rm -v ${{ github.workspace }}:/katalon/katalon/source katalonstudio/katalon \
          katalonc -noSplash -runMode=console \
          -projectPath="/katalon/katalon/source/Demo CI CD.prj" \
          -testSuitePath="Test Suites/Test suites 1" \
          -reportFolder="Reports" \
          -reportFileName="report" \
          -executionProfile="default" \
          -apiKey="${{ secrets.KATALON_API_KEY }}"
