name: Postman API Tests (via Postman API)

on:
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 2. Install Newman
      - name: Install Newman
        run: npm install -g newman

      # 3. Download Collection from Postman API
      - name: Download Postman Collection
        run: |
          curl --location --request GET \
          "https://api.getpostman.com/collections/${{ secrets.POSTMAN_COLLECTION_ID }}" \
          --header "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" \
          --silent | jq '.collection' > collection.json

      # 4. Run Newman Tests
      - name: Run Newman Tests
        run: newman run collection.json --reporters cli,html --reporter-html-export newman-report.html

      # 5. Upload HTML Report as Artifact
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: newman-html-report
          path: newman-report.html
