name: Run Postman Collection

on:
  workflow_dispatch:

jobs:
  run-postman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Newman and HTML Reporter
        run: npm install -g newman newman-reporter-htmlextra

      - name: Download Postman Collection
        run: |
          curl --location \
          --request GET "https://api.getpostman.com/collections/${{ secrets.POSTMAN_COLLECTION_ID }}" \
          --header "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" \
          --output collection.json

      - name: Run Postman Collection with Newman
        run: |
          mkdir -p reports
          newman run collection.json \
            --reporters cli,json,htmlextra \
            --reporter-json-export reports/newman-report.json \
            --reporter-htmlextra-export reports/newman-report.html

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: postman-test-reports
          path: reports/



